### ISSUE TITLE
Make available on Packagist

### ISSUE THREAD

**Issue by nivv** [gazsp/baum#1]
As the title suggests

**Comment by mbardelmeijer** [comment]
+1

**Comment by SuperSeb92** [comment]
+1, would be great

**Comment by gazsp** [comment]
Will do. 

I've got some failing tests to fix first, then I'll add it on Packagist.

**Comment by SuperSeb92** [comment]
I had a quick look into the issues, it's a Laravel bug, fixed in commit https://github.com/laravel/framework/commit/acf0fb9bbf24972defafc2844b9a524e0855306e 

Updating to the latest version of Laravel fixes the failing tests

**Comment by gazsp** [comment]
@SuperSeb92 Good spot. I've updated composer.json and submitted the repo to Packagist.
