### ISSUE TITLE
Support for changing connection.

### ISSUE THREAD

**Issue by bmitch** [gazsp/baum#11]
I'm currently having an issue where I change the connection in the model I have that extends the Node class and call the `rebuild()` method.

When rebuilding it seems to always use the default connection even after I've set the connection on my model. Something like:

```
$this->myModelThatExtendsNode->setConnection('foobar');
$this->myModelThatExtendsNode->rebuild();
```

Since my default database connection is not where the table for the model is I get an error like `SQLSTATE[42S02]: Base table or view not found: 1146 Table 'default.table_for_my_model_that_extends_node'`

I think the reason for this is inside the rebuild() method a new static is created in the constructor for SetBuilder and that new static has the database connection set to the default DB.

I can try to put together a fix but wanted to see if anyone else has run into this and has any other suggestions/

**Comment by gazsp** [comment]
@bmitch Could you try this?

```php
use Baum\SetBuilder;

$node>setConnection('foobar');
$builder = new SetBuilder($node);
$builder->rebuild();
```

Unfortunately fixing this for you would require an API change (as Node::rebuild is static), so I'd rather work around it for the time being.

**Comment by bmitch** [comment]
Thanks @gazsp I will try that. I managed to get around it in my situation (for now) by changing the default DB connection just before I call rebuild() and then setting the default DB connection again just after the call to rebuild().

**Comment by bmitch** [comment]
@gazsp I tried your suggestion above but it still fails. I think because of `isValidNestedSet()` in Node.php where it creates a new SetValidator:

```
  public static function isValidNestedSet() {
    $validator = new SetValidator(new static);

    return $validator->passes();
  }
```

It's creating a new static here which is probably the reason the connection is not retained.

**Comment by gazsp** [comment]
@bmitch How does it fail exactly? Can you provide a stack trace? Thanks.

**Comment by poing** [comment]
#### Under New Management

Focusing support for later Laravel versions.

Cleaning up and closing some of the *really old* issues.  Things that **might** still be a problem will be transfered to a consolidated issue.
