### ISSUE TITLE
[ReflectionException] Class path.database does not exist

### ISSUE THREAD

**Issue by latelatelate** [gazsp/baum#12]
Hi! Thanks for forking this and fixing things. I'm getting a weird issue when trying to install this package with Lumen:

`php artisan baum:install MODEL`

this error is thrown:

`[ReflectionException] Class path.database does not exist`

Setup everything correctly AFAIK, (composer require, added service provider, etc). What could cause this?

**Comment by bmitch** [comment]
Got the same thing here. Looks like it's failing in getMigrationsPath() in `Baum/Console/InstallCommand.php`
