### ISSUE TITLE
Seeding/mass assignment not update orders correctly

### ISSUE THREAD

**Issue by trinvh2** [gazsp/baum#16]
When I use seeding/mass assignment for update items's order. It not working.
On client side I use http://dbushell.github.io/Nestable/ for reordering items.

My code based on readme:

```
$root = Menu::root();
$root->makeTree($request->get('items'));
// Menu::rebuild();
```

It only update children/parent, the order not effected.

**Comment by trinvh** [comment]
Hi, i found a temporary solution by modifying method mapTreeRecursive in SetMapper.php
`protected function mapTreeRecursive(array $tree, $parentKey = null, &$affectedKeys = []) {
		foreach ($tree as $index => $attributes) {
			$node = $this->firstOrNew($this->getSearchAttributes($attributes));
			$data = $this->getDataAttributes($attributes);
			if (!is_null($parentKey)) {
				$data[$node->getParentColumnName()] = $parentKey;
			}
			$node->fill($data);

			// Reordering
			$node->setAttribute($node->getLeftColumnName(), $index);

			$result = $node->save();

			if (!$result) {
				return false;
			}

			$affectedKeys[] = $node->getKey();

			if (array_key_exists($this->getChildrenKeyName(), $attributes)) {
				$children = $attributes[$this->getChildrenKeyName()];

				if (count($children) > 0) {
					$result = $this->mapTreeRecursive($children, $node->getKey(), $affectedKeys);

					if (!$result) {
						return false;
					}
				}
			}
		}

		return true;
	}`

After do that, call Model::rebuild(), it automatically update valid left column value.

**Comment by pawel-damasiewicz** [comment]
You can check https://github.com/gazsp/baum/pull/18

**Comment by poing** [comment]
#### Under New Management

Focusing support for later Laravel versions.

Cleaning up and closing some of the *really old* issues.  Things that **might** still be a problem will be transfered to a consolidated issue.
