### ISSUE TITLE
Returning tree with ancestors collection for each node, like breadcrumbs

### ISSUE THREAD

**Issue by fabiopili** [gazsp/baum#20]
Hello.

First of all, thank you for continuing the work on this package. Having implement a nested set library from scratch in the past, it's great to rely on a better thought out and tested package.

I'm struggling here trying to return the ancestors along with each node on a nested set. For example, each result for the descendantsAndSelf() method would have a sub collection with its full path to the root node represented by the ancestors() method. This would be extremely useful to return the breadcrumbs for each node, for example. Something that could be chained like descendantsAndSelf()->withAncestors().

Doing this with a loop after returning the main query is super simple, but I stumble upon a n+1 problem. I need to solve this in a way that can rely on eager loading and be processed with the main query.

Any pointers or suggestions?

Thank you in advance,

**Comment by poing** [comment]
#### Under New Management

Focusing support for later Laravel versions.

Cleaning up and closing some of the *really old* issues.  Things that **might** still be a problem will be transfered to a consolidated issue.
