### ISSUE TITLE
remove inheritance, use Trait

### ISSUE THREAD

**Issue by peetersdiet** [gazsp/baum#29]
I am interested in using a version of Baum based on Traits. Baum looks well-featured, but we cannot use it by extending from it, because that would break our architecture.

At first glance, I don't really see a blocking issue to introduce Traits. In essence, all Baum\Node code should be moved into a separate Trait. You can then have Baum\Node use that trait, to provide backwards compatibility. If testing with instanceof is an issue, a Node-interface can be created to test on that interface.

In short, some refactoring is necessary to achieve the following pattern:

``` php
namespace Baum;

interface NodeInterface {
    // method signatures from Baum\Node
}

trait NodeTrait {
    // implementation from Baum\Node
}

// only necessary for BC
abstract class Node implements NodeInterface {
    use NodeTrait;
}
```

I'm not really in a position to assess the amount of work involved, but it seems like a straightforward refactoring. And I do not see any drawbacks, as this will be BC and makes the library more flexible in use.

If you're open to my proposed change, I can do the modifications and create a PR.

**Comment by gazsp** [comment]
Sounds good. I'm open to this.

There's a whole other bunch of issues I need to look at, and as this is a BC, we'll probably get some more fixes / updates in place and bump the version to 2.0.

If anybody has any objections to this refactoring (and breaking change), please speak now, or forever hold your peace :-)

**Comment by neyaoz** [comment]
I am going to take this job. But still not sure that which base should I start from?

https://github.com/gazsp/baum vs https://github.com/Sithira/baum

@gazsp Have you checked his doings?

**Comment by gazsp** [comment]
@neyaoz I've not checked other forks, no. 

Feel free to go ahead and work on this, but checkout feature/2.0 and do the work there please. Work can be back-ported to the 1.x branches if requested.

**Comment by poing** [comment]
#### Under New Management

Focusing support for later Laravel versions.

Cleaning up and closing some of the *really old* issues.  Things that **might** still be a problem will be transferred to a consolidated issue.
