### ISSUE TITLE
Wrong Query

### ISSUE THREAD

**Issue by pawel-damasiewicz** [gazsp/baum#3]
In line https://github.com/gazsp/baum/blob/master/src/Baum/Node.php#L724 shouldn't be 
``` php
->where($this->getRightColumnName(), '<', $this->getRight())
```

**Comment by nivv** [comment]
@pawel-damasiewicz what should it be then? :smile:

**Comment by gazsp** [comment]
@nivv Indeed. At a quick glance this looks fine to me. 

@pawel-damasiewicz Care to elaborate further? A failing unit test would be a good start.

**Comment by gazsp** [comment]
No feedback. Closed.
