### ISSUE TITLE
dynamically change the column values

### ISSUE THREAD

**Issue by fayis003** [gazsp/baum#35]
Hi I have a special case where I need the left, right, parent, depth columns to be mapped to other columns in the same table dynamically to get two different tree structures. I tried setting the column properties to custom values as the first step of my experiment but it seems even if I changed the column names in the extended model it still referring the old columns and its not working. What I need actually trying to achieve is to get two types of nested set based on two specific columns say parent_id and sponsor_id etc. Hope you guys have some solutions. 
Thanks

**Comment by nivv** [comment]
You want to change them dynamically on run time? I think that's impossible.

Have you tried below?

```
class YourModel extends Baum\Node {

  protected $table = 'dictionary';

  // 'parent_id' column name
  protected $parentColumn = 'sponsor_id';

  // 'lft' column name
  protected $leftColumn = 'lidx';

  // 'rgt' column name
  protected $rightColumn = 'ridx';

  // 'depth' column name
  protected $depthColumn = 'nesting';

  // guard attributes from mass-assignment
  protected $guarded = array('id', 'parent_id', 'lidx', 'ridx', 'nesting');

}
```
