### ISSUE TITLE
Method Baum\Console\InstallCommand::handle() does not exist

### ISSUE THREAD

**Issue by cff2007** [gazsp/baum#44]
problem here for Laravel 5.5

**Comment by ramiawadallah** [comment]
The same Problem for me

**Comment by dhildreth** [comment]
Looks like same issue with original baum/baum package:
https://github.com/etrepat/baum/issues/283#issuecomment-328862559

I verified the temporary fix of changing the function `fire()` to `handle()` works for me.  This is a bad fix though.

Instead, probably should use Laravel's `dev-backward-support` as mentioned here:
https://github.com/the-control-group/voyager/issues/1624
