### ISSUE TITLE
new item adding issue

### ISSUE THREAD

**Issue by amin101** [gazsp/baum#5]
if try to add a new tree to database using `buildTree()` method and the tree has `left` and `right` but not `id` , it will change new item's and its parent's `left` and `right` by itself.
i think this job should be done only when there are no `left` and `right` attributes, because there are jquery plugins such as nestedSortable that do this job perfectly at client side ,so performing it at server side for second time will disarrange menu order <br/>
example:
comments  are values after saving in database using `buildTree` method 
       
     $menu_cc = [
            [ 'id' => 1, 'parent_id' => null, 'left' => 1, 'right' => 4//8, 'name' => 'r1' ],
             [ 'id' => 2, 'parent_id' => 1, 'left' => 4 , 'right' => 5, 'name' => 'm2'] 
            [ 'id' => null, 'parent_id' => 1, 'left' => 2//6 , 'right' => 3//7, 'name' => 'm3'] 
          ];

**Comment by gazsp** [comment]
```buildTree()``` isn't designed to work with left / right values. It builds the tree structure based on the parent_id of the entries in the array. Just set the parent_id fields to the correct values and it should take care of setting left / right for you.

If you want to update left / right values yourself, just ```save()``` the nodes to the database.

**Comment by amin101** [comment]
Ok,lets say we have a menu containing submenus:

root
-------sub1
-------sub2


    $menu_cc = [
        [ 'id' => 1, 'parent_id' => null, 'name' => 'root' ],
         [ 'id' => 2, 'parent_id' => 1, 'name' => 'sub1'] 
        [ 'id' => 3, 'parent_id' => 1, 'name' => 'sub2'] 
       ];

if i try to add a new subitem between `sub1` and `sub2` : 

       $menu_cc = [
         [ 'id' => 1, 'parent_id' => null, 'name' => 'root' ],
         [ 'id' => 2, 'parent_id' => 1, 'name' => 'sub1'] ,
         [ 'id' => 2, 'parent_id' => 1, 'name' => 'sub3'] ,//note this submenu should be between sub1 & sub2
         [ 'id' => 3, 'parent_id' => 1, 'name' => 'sub2'] 
        ];

then update the tree using `buildTree()` , it doesnt care about order of submenus and add new sub3  as the last sub of tree.
