### ISSUE TITLE
L5.6 baum:install issues

### ISSUE THREAD

**Issue by zhi8617** [gazsp/baum#54]
ver dev-feature/2.0
 When run "php artisan baum:install" command . 
will get the error
Class 'Baum\Console\BaumCommand' not found .
 ( Providers/BaumServiceProvider.php:46 ) 

Is this package development still in progress??

**Comment by gazsp** [comment]
It is - although I'm very busy with other projects at the moment! Also, the 2.0 branch still isn't fully working / tested, but thanks for the heads up.

Feel free to submit a pull request that fixes this :-)

**Comment by gazsp** [comment]
Fixed in develop/2.0 branch
