### ISSUE TITLE
how to get hierarchy with relations?

### ISSUE THREAD

**Issue by aske-cph** [gazsp/baum#6]
Thanks for continuing the repo!

I can't seem to get the complete hierarchy tree with the relations intact.

		$tree = Group::where('id', '=', $id)
		->with(['users')
		->first()
		->getDescendantsAndSelf()
		->toHierarchy();

The tree is written out but the users aren't there.

**Comment by aske-cph** [comment]
To answer my won question:

		$tree = Group::where('id', '=', $id)
		->first()
		->descendantsAndSelf()
		->with('users')
		->get()
		->toHierarchy();

**Comment by hungnm144** [comment]
how to retrieve all descendants with a `where clause`? ex: 
$tree = Group::where('id', '=', $id)
    ->first()
    ->descendantsAndSelf()->where('active', true) // Get all children are activated
    ->with('users')
    ->get()
    ->toHierarchy();
I wrote and try it but not work
