### ISSUE TITLE
What's the solution for large number of data?

### ISSUE THREAD

**Issue by phpspider** [gazsp/baum#62]
What's the solution for large number of data? My PHP script gets timeout as i have 1 Million records in my database. I am creating child of root node which is old node as per the created date it's updating lft and rgt values for all records.

**Comment by phpspider** [comment]
@gazsp any suggestion?

**Comment by poing** [comment]
I'm not too clear what's under the hood, regarding the `lft` and `rgt` values.  *But I can offer some suggestions.*

*At a minimum* `moveLeft()` and `moveRight()` *should only* affect **direct** children of a `parent` node.  *I hope that's the case!*

Do you have a large number of children for a *single* node?

Have you tried creating an `index` for each field in the `Model`?

*I'm also curious, are you using Eloquent relationships -or- expanding the `Model` with additional fields?*

**Comment by phpspider** [comment]
I've around 7 million records. When I am going to create children of the very first record then Baum is updating or rebuilding the tree and updating values lft and rgt values for all the records. So updating all the lft and rgt values for around 7 million records php script is getting timeout.

**Comment by poing** [comment]
Have you tried creating an `index` for each field in the migration?

```php
    $table->index('id');
    $table->index('parent_id');
    $table->index('lft');
    $table->index('rgt');
    $table->index('depth');
```
*This might help speed things up.  But it's **only** a short term solution.*

----

There is an *underling* issue, where your 7 million records are maintained in a *pseudo*-numerical order.  `lft` and `rgt` change in relation to **all** the other records.  It's *simply* how `gazsp/baum` maintains the tree.

**Even if** the *pseudo*-numerical order for `lft` and `rgt` was removed, only depending on `siblings()`, there *would* still be issues with data sets that have breadth.  *Lot's of `siblings()` under a single parent.*

----

Seems like you *may* have reached a limitation of `gazsp/baum`.  *After-all*, it's **just** a lightweight [DAG](https://en.wikipedia.org/wiki/Directed_acyclic_graph).  

You *may* need to look at something that *could* scale better, like [OQGRAPH](https://mariadb.com/kb/en/library/oqgraph-overview/) for MariaDB *-or-* `telkins/laravel-dag-manager` for Laravel (*not sure how it scales*).

**Comment by gazsp** [comment]
This sounds like a case where having multiple trees (breaking up the tree to have multiple root nodes) might help. Also adding indexes (as previously mentioned) would help as well.

I’m really busy with other projects at the moment, so don’t currently have the time to look in this further I’m afraid.
