### ISSUE TITLE
Event Dispatcher Contract fire() method removal support

### ISSUE THREAD

**Issue by DanWithams7d** [gazsp/baum#65]
In later version of laravel after 5.5 the EventDispatch contract was changed so that fire() is no longer the method for dispatching events. This was changed to dispatch()

We should support this throughout the package

**Comment by DanWithams7d** [comment]
I've created a PR to fix this;

https://github.com/gazsp/baum/pull/64

**Comment by alalfakawma** [comment]
Please pull this @gazsp, really needed for Laravel 5.8

**Comment by Lunatig** [comment]
@gazsp please

**Comment by gazsp** [comment]
Done

**Comment by appdezign** [comment]
@gazsp Please merge this to the master branch. I would also like to use this in production for a Laravel 5.8 app.

**Comment by poing** [comment]
#### Under New Management

Focusing support for later Laravel versions.

Cleaning up and closing some of the *really old* issues.  Things that **might** still be a problem will be transferred to a consolidated issue.
