### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by gazsp** [gazsp/baum#66]
Hi all.

I've moved on to other things, and am not actively using or developing Baum at the moment. Is anybody interested in becoming the main package maintainer? Preferably someone who is actively using the package in a Laravel 5.8 app...

CI builds are broken, and the next version needs releasing to Packagist once everything has been cleaned up with unit tests / CI verified as working.

Cheers,
Gaz.

**Comment by poing** [comment]
Hi Gaz,

Since I have a couple projects using Baum, I'm willing to help maintain the project.  _You can contact me directly, mail address in my profile._ 


Sincerely,
Brian LaVallee

**Comment by poing** [comment]
Hi Gaz,
Have not heard back from you!  Can you please reach out?

Brian

**Comment by gazsp** [comment]
I've just invited you to the project - please feel free to run with it as you wish :-)
