### ISSUE TITLE
laravel 7

### ISSUE THREAD

**Issue by scwall** [gazsp/baum#81]
Hello, 
I come from python/django and we have the excellent mptt https://github.com/django-mptt/django-mptt for tree management. I'm currently working on a laravel project where I have to integrate the equivalent, I have a lot of data to save on the tree I found the library: https://github.com/lazychaser/laravel-nestedset, but this one is horrible in terms of performance, it's not very user friendly (don't integrate the depth in the database, even after 50 requests ...., especially as it could solve some of the problems). After several researches the Baum library seems to me the closest to what I need in terms of quality and performance. Now I could see that it is not available for laravel 7, will you adapt it for laravel 7 ?
I could see on this post https://github.com/etrepat/baum/pull/332 that @mkwsra has been asking for a traction for a while couldn't there be a work between you ?
Thank you in advance

**Comment by poing** [comment]
@scwall you'll find that branch `2.0.2` does *actually* work with Laravel 7.  I am using it myself in some projects.  

Testbench 5.x [tests](https://travis-ci.org/github/gazsp/baum) are run using Laravel 7.


<img width="879" alt="Screen Shot 2020-12-17 at 7 52 33" src="https://user-images.githubusercontent.com/11417007/102416309-eb032780-403c-11eb-9a58-1c96ab9ecd7b.png">

When I have time, I have been trying to improve test coverage.  `2.0.3` is at `80%`

<img width="363" alt="Screen Shot 2020-12-17 at 7 50 13" src="https://user-images.githubusercontent.com/11417007/102416146-9eb7e780-403c-11eb-90c8-1bfbb72c4980.png">

**Comment by scwall** [comment]
@poing 
Thank you for your answer. I just saw it just now.  😄 
I used this to add it to my project, did you proceed the same way or is there another way?
```
"repositories": [
    {
      "type": "package",
      "package": {
        "name": "baum/v2",
        "version": "2",
        "type": "baum-three",
        "source": {
          "url": "https://github.com/etrepat/baum/",
          "type": "git",
          "reference": "v2"
        }
      }
    }
  ],
  "require": {
    "php": "^7.2.5",
    "baum/v2": "^2", 
```
Thank you in advance

**Comment by poing** [comment]
Use: `composer require gazsp/baum:2.0.*`

`etrepat/baum` is *depreciated* and has been forked **long ago**.

**Comment by scwall** [comment]
Perfect :+1: thanks @poing
